/**
 * seed-healing.ts — Schema Therapy Only (18 books)
 *
 * Seeds the `hp` collection in MongoDB `hope` database.
 * Every record drawn from the 18-book schema therapy library.
 * Focused on Unrelenting Standards, Subjugation (Rebel), Failure.
 *
 * Run: export $(grep MONGODB_URI .env.local | xargs) && pnpm tsx scripts/seed-healing.ts
 */

import { MongoClient } from "mongodb";

interface HealingRecord {
  id: string;
  source: string;
  sourceShort: string;
  framework: "schema_therapy";
  concept_type: string;
  name: string;
  description: string;
  mechanism: string;
  schemaRelevance: string[];
  tags: string[];
  practice: { what: string; how: string; when: string; duration: string; frequency: string; successMarker: string };
  contraindication?: string;
  progressionFrom?: string;
  progressionTo?: string;
}

const records: HealingRecord[] = [
  {id:"ST-01",source:"Schema Therapy: A Practitioner's Guide — Young, Klosko & Weishaar (2003)",sourceShort:"Practitioner's Guide",framework:"schema_therapy",concept_type:"core_emotional_needs",name:"Core Emotional Needs Inventory — Personal Mapping",description:"Identify which of the five core emotional needs were unmet in childhood: (1) Secure attachment, (2) Autonomy and competence, (3) Freedom to express needs and emotions, (4) Spontaneity and play, (5) Realistic limits. For Unrelenting Standards: autonomy was conditional on performance. For Subjugation: freedom to express needs was physically blocked.",mechanism:"Young's foundational principle: schemas form when core emotional needs go unmet. Healing requires identifying WHICH needs were frustrated, then finding age-appropriate ways to meet them now. The patient's observation-based schema reveals frustrated need #2 — autonomy and competence were made conditional on excellence, not given unconditionally.",schemaRelevance:["Unrelenting Standards","Subjugation","Failure"],tags:["core_needs","foundation","assessment","unmet_needs","autonomy","attachment","Young"],practice:{what:"Map your five core emotional needs — which were met, which were frustrated, and how",how:"Write five sections. (1) Secure attachment: 'Was I safe with caregivers?' — Father's anxiety created unpredictable restrictions; mother's frustration displaced physically. (2) Autonomy/competence: 'Was I encouraged to be capable on my own terms?' — Competence was the ONLY path to belonging — observed as survival requirement. (3) Freedom to express needs: 'Could I say what I needed?' — Dynamic child tied to beam. Needs physically prevented. (4) Spontaneity/play: 'Was play allowed?' — Play was what got restricted. Going outside was dangerous. (5) Realistic limits: 'Were boundaries reasonable?' — Father's limits were anxiety-based, not realistic. Rate each 0-10.",when:"One dedicated session. Foundation work — do this before any other exercise.",duration:"45 minutes",frequency:"Once. Revisit after 3 months.",successMarker:"You can name the exact developmental gap behind each schema without intellectualizing. The map feels emotionally true, not just analytically correct."},progressionTo:"ST-02"},
  {id:"ST-02",source:"Breaking Negative Thinking Patterns — Jacob, van Genderen & Seebauer (2015)",sourceShort:"Breaking Neg. Thinking",framework:"schema_therapy",concept_type:"schema_mode_identification",name:"Schema Mode Mapping — Real-Time Self-Monitoring",description:"Learn to identify which mode you operate from in real time. Key modes: Demanding Parent ('Be exceptional'), Vulnerable Child ('I'll be pushed out'), Angry/Rebel Child ('No one controls me'), Detached Protector ('Feel nothing'), and the target: Healthy Adult.",mechanism:"Jacob et al.'s mode model: everyone shifts between modes throughout the day. Mode awareness prevents fusion — when the Rebel takes over, naming it as a MODE creates distance. The Healthy Adult can observe all other modes without being controlled by any of them. This IS the third state.",schemaRelevance:["Unrelenting Standards","Subjugation","Failure"],tags:["mode_map","mode_identification","real_time","Demanding_Parent","Rebel_Child","Healthy_Adult","Jacob"],practice:{what:"Create your personal mode map and track mode shifts three times daily",how:"Draw your mode map with YOUR modes: (1) Demanding Parent: 'You must be exceptional. Ask for guidance and you're weak.' (2) Vulnerable Child: 'I'll be marginalized if I'm not the best.' (3) Angry/Rebel Child: 'No one tells me what to do.' (4) Detached Protector: emotional shutdown, work-only. (5) Healthy Adult: 'I see the situation clearly. My job requires X. I do X.' Set three daily alarms. At each: name current mode. Log it.",when:"Create map once. Track three times daily.",duration:"30 min to create. 30 seconds per check-in.",frequency:"Daily tracking for 6 weeks.",successMarker:"You catch a mode shift AS it happens rather than recognizing it hours later."},progressionFrom:"ST-01",progressionTo:"ST-03"},
  {id:"ST-03",source:"Schema Therapy in Practice: Mode Approach — Arntz & Jacob (2013)",sourceShort:"Mode Approach",framework:"schema_therapy",concept_type:"mode_cycle_interruption",name:"Mode Cycle Interruption — Breaking the Activation Chain",description:"Map the mode cycle: Trigger → Vulnerable Child → Demanding Parent escalates → Coping mode fires (Rebel OR Detached Protector) → Aftermath. Insert Healthy Adult BETWEEN Vulnerable Child and coping response.",mechanism:"Arntz & Jacob's mode cycle model: schemas trigger a predictable sequence. Boss gives instruction → Vulnerable Child feels controlled → Demanding Parent says 'Prove yourself' → Rebel fires → Conflict → Failure → shame. The intervention point is between Vulnerable Child and coping mode — that's where the Healthy Adult steps in.",schemaRelevance:["Unrelenting Standards","Subjugation"],tags:["mode_cycle","interruption","chain","Arntz","Jacob","activation_sequence"],practice:{what:"Map your mode cycle for authority interactions, then practice the interruption",how:"Write the chain: (1) Trigger: Mehdi gives instruction. (2) Vulnerable Child: 'I'm being controlled.' (3) Demanding Parent: 'You should already know this.' (4) Rebel: 'He has no right.' (5) Counterattack or shutdown. NOW insert step 3.5: Healthy Adult — 'I notice the Vulnerable Child. The Rebel is about to fire. PAUSE. What does this situation actually need? It needs: Understood, I'll consult before externalizing.' Practice this chain on paper five times, then mentally when calm, then in real situations.",when:"Map once. Mental rehearsal daily. Apply in every authority interaction.",duration:"20 min to map. 5 min rehearsal. 10 seconds real-time.",frequency:"Daily rehearsal for 4 weeks. Real-time ongoing.",successMarker:"The Healthy Adult inserts itself automatically between Vulnerable Child and Rebel. The full cycle doesn't complete."},progressionFrom:"ST-02"},
  {id:"ST-04",source:"Schema Therapy: Distinctive Features — Rafaeli, Bernstein & Young (2011)",sourceShort:"Distinctive Features",framework:"schema_therapy",concept_type:"limited_reparenting",name:"Self-Reparenting — Letter to the Vulnerable Child",description:"Write a letter from your Healthy Adult to your Vulnerable Child, meeting the specific unmet need. For observation-based Unrelenting Standards, the unmet need is: 'you are safe without being exceptional.'",mechanism:"Limited reparenting is the core change mechanism in schema therapy (Rafaeli et al., Point 14). In self-directed work, the Healthy Adult takes this role. For ego-syntonic schemas formed by the patient's own observation, the reparenting must honor the intelligence of the original strategy while updating it.",schemaRelevance:["Unrelenting Standards"],tags:["limited_reparenting","letter","Vulnerable_Child","Healthy_Adult","Rafaeli"],practice:{what:"Write a letter from your Healthy Adult to the boy who watched the family system",how:"'I see what you saw. The oldest sister excelled and was gathered. The others were pushed to the edges. You read that system perfectly — you were the smartest person in that house. And you made the only conclusion available: if I excel, I stay inside the circle. That conclusion saved you. But here is what you couldn't know: that house is not the world. AVIS is not the family. Mehdi is not the father. You have already proven competence — eight months, eight regulation successes. You don't have to prove it again every morning. You can be ordinary today and still belong.'",when:"30+ uninterrupted private minutes. Not during activation.",duration:"30-45 min writing. 10 min to sit with it.",frequency:"Write once. Re-read weekly. Rewrite when new understanding emerges.",successMarker:"Emotional response while writing — tears, tightness, relief. If nothing, you're in Detached Protector. Try again when more open."},contraindication:"Not during crisis or within hours of activation.",progressionTo:"ST-05"},
  {id:"ST-05",source:"Cambridge Guide to Schema Therapy — Cockram, Drummond & Lee (2022)",sourceShort:"Cambridge Guide",framework:"schema_therapy",concept_type:"limited_reparenting",name:"Self-Reparenting for Subjugation-Rebel — Validating the Dynamic Child",description:"The Rebel is the dynamic child physically controlled — tied to beam, prevented from going outside. Reparenting means validating the child's RIGHT to have needs while teaching the adult that instructions at work are not the beam.",mechanism:"The Cambridge Guide emphasizes that core need #3 (freedom to express needs) must be addressed directly. For Subjugation-Rebel, the unmet need is autonomy with safety. The child could not be autonomous AND safe. The Rebel swings to the opposite: any constraint = the beam. Reparenting validates the original need while updating the equation.",schemaRelevance:["Subjugation"],tags:["limited_reparenting","Subjugation","Rebel","autonomy","beam","Cambridge"],practice:{what:"Write a dialogue between Healthy Adult and Rebel Child about authority",how:"Rebel: 'Mehdi has no right to tell me to check before deciding.' Healthy Adult: 'I hear you. But ask yourself: would you object if this was YOUR idea? If consulting first was your decision, would it feel like control?' Rebel: '...No.' Healthy Adult: 'Then the objection is to being TOLD, not to the content. That is the beam talking — the boy who was tied down. That anger is real. But Mehdi is not the father. This office is not that house. You can follow guidance AND keep your autonomy.'",when:"After any Subjugation-Rebel activation, once calm.",duration:"15-20 minutes",frequency:"Once per Rebel activation. Review past dialogues weekly.",successMarker:"The Rebel starts pausing before firing. The Healthy Adult voice appears in real-time."},progressionFrom:"ST-04"},
  {id:"ST-06",source:"Schema Therapy for BPD 2nd Edition — Arntz (2024)",sourceShort:"Arntz BPD 2nd",framework:"schema_therapy",concept_type:"imagery_rescripting",name:"Imagery Rescripting — The Classroom Scene",description:"Return in imagery to the classroom where you couldn't say 'I don't understand' and rescript it: the adult you enters, protects the child, provides permission to not know.",mechanism:"Arntz describes imagery rescripting as the primary experiential technique. It works through memory reconsolidation: re-accessing the emotional memory while introducing new information updates the memory trace. For observation-based schemas, rescripting must address the CONCLUSION the child drew, not just the feeling.",schemaRelevance:["Unrelenting Standards","Failure"],tags:["imagery_rescripting","experiential","classroom","Arntz","memory","emotional_processing"],practice:{what:"Guided self-imagery: return to the classroom and rescript the scene",how:"Close eyes. Picture yourself as the boy who couldn't say 'I don't understand.' See the teacher, the pressure. Feel the vigilance. Now: the adult you walks in, sits next to the boy, says: 'You don't have to pretend you understand. I know you're scared that if they see you don't know, you'll be pushed away like the sisters. But this classroom is not the family. And even if they judge — I am here. I will not let you disappear.' Let the boy respond. Stay until emotional intensity decreases 50%.",when:"Calm, private, emotionally available. NOT in Detached Protector mode.",duration:"20-30 minutes",frequency:"Monthly for the classroom scene. Create new rescriptings for DEKRA, the beam.",successMarker:"The emotional charge of the memory decreases. You feel sadness and compassion rather than anxiety and urgency."},contraindication:"If you dissociate, stop and ground. Ideally done with a therapist. Self-directed only if you maintain Healthy Adult perspective."},
  {id:"ST-07",source:"Schema Therapy for Memory Reconsolidation — Arntz & Jacob",sourceShort:"Memory Reconsolidation",framework:"schema_therapy",concept_type:"imagery_rescripting",name:"Safe Place Imagery — Building the Soothing System",description:"Create a detailed internal safe place that activates the soothing system. Directly addresses that soothing has been starved — safety was always conditional on performance.",mechanism:"Safe place imagery creates a competing emotional memory activated when the threat system fires. For patients where soothing was starved, the safe place is the first experience of safety without performance. Travel memories since Super Auto may work — places where the mother's warmth system was active.",schemaRelevance:["Unrelenting Standards","Subjugation"],tags:["safe_place","imagery","soothing_system","Gilbert","threat_reduction","memory_reconsolidation"],practice:{what:"Build a safe place image and practice activating it daily",how:"Choose a place — real or imagined — where you feel safe WITHOUT performing. Close eyes. Build it: See, hear, smell, feel. The KEY: no one is evaluating you here. You are simply present. Spend 5 min inside. If the Demanding Parent pulls you out ('You should be productive'), name it: 'That's the Demanding Parent. In this place, he has no authority.' Return.",when:"Daily, same time. Also as emergency anchor during activation.",duration:"5 min daily. 30 seconds as emergency anchor.",frequency:"Daily for 8 weeks. Then as needed.",successMarker:"You activate the safe place in under 10 seconds. Your body relaxes. The soothing system has a reliable entry point."},progressionTo:"ST-06"},
  {id:"ST-08",source:"Contextual Schema Therapy — Roediger, Stevens & Brockman (2018)",sourceShort:"Contextual ST",framework:"schema_therapy",concept_type:"chair_work",name:"Chair Dialogue — Demanding Parent vs Healthy Adult",description:"Empty chair technique to externalize and confront the Demanding Parent. Physically sit in different chairs for different modes. Physical movement creates embodied separation.",mechanism:"Roediger's Contextual ST emphasizes chair work as primary experiential technique. Moving between chairs prevents fusion — the Demanding Parent is in a DIFFERENT PLACE than the Healthy Adult. For ego-syntonic Unrelenting Standards, chair work makes it visible as a separate entity.",schemaRelevance:["Unrelenting Standards","Subjugation"],tags:["chair_work","dialogue","Demanding_Parent","Healthy_Adult","Roediger","experiential"],practice:{what:"Set up three chairs: Demanding Parent, Vulnerable Child, Healthy Adult",how:"Chair 1 (Demanding Parent): 'You must be the best. If you ask for help, they'll see you're weak.' Chair 2 (Vulnerable Child): 'I'm so tired of proving myself every day.' Chair 3 (Healthy Adult): 'I hear both of you. Demanding Parent — you kept us safe as a child. But you're running rules from a house 20 years ago. Vulnerable Child — your exhaustion is real. Here is what I will do: next time Mehdi instructs, I respond to CONTENT, not to the feeling of control.' Cycle until Healthy Adult has the final word.",when:"Weekly, in private. Especially after strong activations.",duration:"20-30 minutes",frequency:"Weekly for 8 weeks. Then after significant activations.",successMarker:"Healthy Adult voice becomes stronger. You feel the difference between modes in your body."}},
  {id:"ST-09",source:"Experiencing Schema Therapy from the Inside Out — van Vreeswijk, Broersen & Nadort (2012)",sourceShort:"Experiencing ST",framework:"schema_therapy",concept_type:"chair_work",name:"Chair Work — Setting Limits to the Inner Critic",description:"Chair work to reduce the Demanding Parent's power. The Healthy Adult confronts the critic, names its origin, acknowledges its function, and explicitly limits its authority.",mechanism:"Van Vreeswijk's SP/SR approach: setting limits to the Inner Critic is not silencing it (triggers Subjugation) but rightful authority transfer. The Healthy Adult says 'I hear you, I know why you exist, but you no longer run this operation.'",schemaRelevance:["Unrelenting Standards"],tags:["chair_work","inner_critic","Demanding_Parent","limit_setting","van_Vreeswijk"],practice:{what:"Confront the Demanding Parent with specific limit-setting",how:"From Healthy Adult chair, address empty Demanding Parent chair: 'I know you. You are the conclusion from watching my sisters. You said: excel or disappear. That was true in that house. But at AVIS, my job is to anticipate, inform, stay in domain. YOU add: be indispensable, control all decisions, never need guidance. Those are YOUR additions, not the job. I am keeping your vigilance — it notices things others miss. But I am removing your authority to define what counts as safe. Good enough IS safe. Asking for guidance IS professional.'",when:"After becoming aware the Demanding Parent has been running unchecked.",duration:"15 minutes",frequency:"Bi-weekly, or after any over-proving week.",successMarker:"The Demanding Parent's messages still arrive but feel like suggestions you can evaluate, not commands."}},
  {id:"ST-10",source:"Reinventing Your Life — Young & Klosko (1993)",sourceShort:"Reinventing Your Life",framework:"schema_therapy",concept_type:"schema_flashcard",name:"Schema Flashcard — Portable Cognitive Anchor",description:"Young & Klosko's flashcard: name the schema, its origin, its lie, the operational truth, and one healthy behavior. Carry and read during activation.",mechanism:"During activation, prefrontal cortex is partially offline. The flashcard provides a pre-prepared counter-narrative readable under emotional load, written by the Healthy Adult when fully online.",schemaRelevance:["Unrelenting Standards","Subjugation","Failure"],tags:["flashcard","cognitive","portable","Young","Klosko","activation","interrupt"],practice:{what:"Create flashcards for your top 3 schema activations",how:"Card 1 — US: Front: 'I feel I must be exceptional. This is the classroom running, not reality.' Back: 'My job: anticipate, inform, stay in domain. The schema adds: be indispensable, never need help. I can work without the additions.' Card 2 — Subjugation: Front: 'I'm objecting to being told, not to the content. This is the beam.' Back: 'Would I object if this was my idea? If no — the Rebel is reacting to STRUCTURE, not content.' Card 3 — Failure: Front: 'I feel like an impostor.' Back: '8 months AVIS. 8+ regulations. Two apps. Architecture mapped. Competence is real.'",when:"Read immediately when activated. Create when calm.",duration:"10 min to create. 30 sec to read.",frequency:"Carry always. Read every activation. Update monthly.",successMarker:"You reach for the card before rumination completes its first loop."}},
  {id:"ST-11",source:"Schema Therapy: A Practitioner's Guide — Young, Klosko & Weishaar (2003)",sourceShort:"Practitioner's Guide",framework:"schema_therapy",concept_type:"cognitive_strategy",name:"Historical Test of the Schema — Evidence Review",description:"Systematically review evidence from entire life that contradicts the schema. The schema maintains itself through confirmation bias. The historical test forces attention to disconfirming evidence.",mechanism:"The patient examines evidence from childhood, adolescence, and adulthood both supporting and contradicting the schema. For ego-syntonic US, the test examines: 'Were there times I was NOT exceptional and NOT marginalized?' The schema predicts never — evidence shows otherwise.",schemaRelevance:["Unrelenting Standards","Failure"],tags:["historical_test","cognitive","evidence","confirmation_bias","Young","disconfirming"],practice:{what:"Conduct a formal historical test of the Unrelenting Standards schema",how:"Three columns across three periods. Childhood: FOR ('Excelling sisters were gathered') vs AGAINST ('I was loved even before I excelled'). DEKRA: FOR ('Competence protected me') vs AGAINST ('Protection cost sleeping at work, unethical compromises, 7 years trapped'). AVIS: FOR ('Being competent earns respect') vs AGAINST ('Mehdi hasn't fired me despite imperfect performance. Othmane incident — held boundary without proving anything exceptional. Regulated email — good enough, world continued.')",when:"One dedicated calm session.",duration:"30-45 minutes",frequency:"Once for main schema. Repeat for Subjugation if needed.",successMarker:"AGAINST column significantly longer than FOR. The schema's prediction ('ordinary = marginalized') is contradicted by your own data."}},
  {id:"ST-12",source:"Schema Therapy: A Practitioner's Guide — Young, Klosko & Weishaar (2003)",sourceShort:"Practitioner's Guide",framework:"schema_therapy",concept_type:"cognitive_strategy",name:"Schema Diary — Daily Activation Log",description:"Young's structured daily log: trigger, schema, mode sequence, coping response, Healthy Adult alternative. The operational backbone of schema therapy homework.",mechanism:"Three functions: (1) Pattern recognition — same schema across situations destroys felt-uniqueness. (2) Mode sequence awareness — makes automatic process visible. (3) Alternative generation — pre-loads Healthy Adult responses. Must be DAILY, not just after big activations.",schemaRelevance:["Unrelenting Standards","Subjugation","Failure"],tags:["schema_diary","daily","log","tracking","Young","homework"],practice:{what:"Keep a daily schema diary",how:"Each evening: (1) Situation (2) Trigger (3) Schema: US, Subjugation, or Failure? (4) Mode sequence: which modes fired? (5) Coping response: what did I do? (6) Healthy Adult alternative (7) Regulation success? Yes/No. Even ONE entry is useful. Even NOTICING no activations is data.",when:"Every evening, 15 min before winding down.",duration:"10-15 minutes",frequency:"Daily for 8 weeks. Then 3x/week minimum.",successMarker:"After 4 weeks, patterns emerge: same schema, same trigger type. You start predicting activations before they fully develop."}},
  {id:"ST-13",source:"Schema Therapy: Distinctive Features — Rafaeli, Bernstein & Young (2011)",sourceShort:"Distinctive Features",framework:"schema_therapy",concept_type:"behavioral_pattern_breaking",name:"Behavioral Pattern-Breaking — Graded Experiments",description:"The third pillar of schema therapy. Deliberately choose behaviors contradicting the schema's demands, starting low-stakes. Replace surrender, avoidance, and overcompensation with HEALTHY behavior.",mechanism:"Schemas maintain through three coping styles: surrender (obeying), avoidance (avoiding triggers), overcompensation (extreme opposite). Pattern-breaking replaces all three with healthy behavior responding to the actual situation.",schemaRelevance:["Unrelenting Standards","Subjugation"],tags:["pattern_breaking","behavioral","experiment","graded","Rafaeli","coping_styles"],practice:{what:"One behavioral experiment per week contradicting the schema",how:"Week 1: Submit ONE task at 80%. Write prediction before, outcome after. Week 2: Ask ONE question you already know the answer to — practice asking without shame. Week 3: Receive ONE instruction and respond 'Understood' without internal rehearsal. Week 4: Leave ON TIME one day without finishing everything. Increase stakes gradually.",when:"Plan Sunday. Execute during week. Log Friday.",duration:"5 min to plan. Task itself. 5 min to log.",frequency:"One per week. Increase to two when easy.",successMarker:"Schema's prediction consistently fails. Library of disconfirming behavioral evidence grows."}},
  {id:"ST-14",source:"The Schema Therapy Clinician's Guide — Farrell & Shaw (2012)",sourceShort:"Clinician's Guide",framework:"schema_therapy",concept_type:"behavioral_pattern_breaking",name:"Healthy Adult Response Templates — Third State Scripts",description:"Farrell & Shaw: build concrete behavioral repertoire for the Healthy Adult. Not principles — exact words. For a patient whose only modes were silence and rebellion, the third state needs actual WORDS.",mechanism:"Building 'functional scripts' that bypass automatic reactions. Templates are not rehearsal (feeds rumination) — they are pre-built tools eliminating the need to simulate.",schemaRelevance:["Subjugation","Unrelenting Standards"],tags:["behavioral","response_templates","Healthy_Adult","scripts","third_state","Farrell","Shaw"],practice:{what:"Build response templates for your top 5 triggers",how:"(1) Boss asks to check: 'Understood, I'll consult before externalizing.' (2) Colleague questions competence: 'Here's my reasoning. Let me know if you see it differently.' (3) Below-level task: 'I'll handle it.' (4) Disagree with decision: 'I see it differently — [one sentence]. Happy to defer.' (5) Don't know something: 'I'm not sure. Let me check.' (6) Need help: 'I'd like your input before I proceed.' Practice aloud 5x each.",when:"Create now. Practice weekly. Review before high-activation situations.",duration:"20 min to create. 5 min to practice.",frequency:"Create once. Practice weekly. Update as needed.",successMarker:"A template fires in a real situation. No 20-minute simulation beforehand."}},
  {id:"ST-15",source:"Schema Therapy: Distinctive Features — Rafaeli, Bernstein & Young (2011)",sourceShort:"Distinctive Features",framework:"schema_therapy",concept_type:"empathic_confrontation",name:"Self-Directed Empathic Confrontation — Compassion + Truth",description:"Hold two truths simultaneously: compassion for why the schema exists AND confrontation of how it damages current life. Neither alone produces change.",mechanism:"Empathic confrontation prevents both collusion and premature confrontation. Self-directed: 'You were right to develop this. AND it is costing you your wellbeing now. Both are true.' Essential for ego-syntonic schemas.",schemaRelevance:["Unrelenting Standards","Subjugation"],tags:["empathic_confrontation","compassion","truth","both_and","Rafaeli","ego_syntonic"],practice:{what:"Practice empathic confrontation in schema diary entries",how:"After each log, add: EMPATHY: 'It makes sense I reacted this way because [trace to origin]. The boy who watched the family system would of course feel ordinary is dangerous.' CONFRONTATION: 'AND this cost me [name cost]. Energy went to image maintenance instead of actual work. The Rebel fired at instruction instead of content.' Both must be present.",when:"In every schema diary entry.",duration:"5 additional min per entry.",frequency:"Every diary entry.",successMarker:"You hold 'This makes sense' and 'This is costly' simultaneously without one collapsing into the other."}},
  {id:"ST-16",source:"Breaking Negative Relationship Patterns — Jacob, van Genderen & Seebauer (2016)",sourceShort:"Breaking Neg. Relationships",framework:"schema_therapy",concept_type:"relationship_pattern",name:"Mode Clash Analysis — Professional Relationships",description:"When two people's modes interact, they create self-reinforcing cycles. Map how your modes interact with authority figures' modes to reveal predictable conflict patterns.",mechanism:"Your Rebel clashing with a boss's Demanding Parent creates mutual escalation. Understanding the MODE CLASH reveals conflict is between two childhood adaptations, not professional positions. Depersonalizes authority conflicts.",schemaRelevance:["Subjugation","Unrelenting Standards"],tags:["relationship","mode_clash","interpersonal","authority","Jacob","depersonalization"],practice:{what:"Map the mode clash pattern with Mehdi",how:"Your mode: Rebel fires at instruction. Authority mode: possibly Demanding Parent or Vulnerable Child. Cycle: Mehdi instructs → Rebel resists → authority escalates → Rebel escalates → conflict. Healthy alternative: Mehdi instructs → Healthy Adult receives content → responds to situation needs → no cycle. Key: you cannot control Mehdi's modes. You CAN respond from Healthy Adult, preventing the clash.",when:"After any authority conflict.",duration:"15 minutes",frequency:"After conflicts. Monthly review.",successMarker:"You see authority conflicts as mode clashes rather than personal attacks. Emotional intensity drops 50%+."}},
  {id:"ST-17",source:"Mindfulness and Schema Therapy — van Vreeswijk, Broersen & Schurink (2014)",sourceShort:"Mindfulness & ST",framework:"schema_therapy",concept_type:"mindfulness_schema",name:"Schema-Focused Mindfulness — Mode Observation",description:"Observe mode shifts as they happen without engaging or suppressing. NOT generic mindfulness — mindfulness with schema-specific mode labels.",mechanism:"Generic mindfulness: 'observe thoughts.' Schema-focused: 'observe the Demanding Parent arising and name it as Demanding Parent, not as truth.' Schema labeling engages the mode model in real-time, creating instant distance.",schemaRelevance:["Unrelenting Standards","Subjugation"],tags:["mindfulness","schema_focused","mode_observation","van_Vreeswijk","labeling"],practice:{what:"5 minutes of schema-focused mindfulness daily",how:"Sit quietly. When a thought appears, label with MODE: 'I should prepare more' → 'Demanding Parent.' 'What if Mehdi thinks...' → 'Vulnerable Child.' 'He has no right' → 'Rebel Child.' 'I don't want to think about work' → 'Detached Protector.' Label. Don't argue, reassure, or suppress. Return to stillness.",when:"Daily, morning. Sets observing stance for the day.",duration:"5 minutes",frequency:"Daily for 8 weeks. 3x/week maintenance.",successMarker:"You label modes in real-time during actual interactions. Labeling creates instant distance."}},
  {id:"ST-18",source:"Emotional Schema Therapy: Distinctive Features — Leahy (2015)",sourceShort:"Emotional Schema Therapy",framework:"schema_therapy",concept_type:"emotional_schema",name:"Emotional Schema Awareness — Beliefs About Your Emotions",description:"Leahy's layer: you have beliefs about your OWN EMOTIONS that maintain schemas. Key: 'My anxiety about competence is evidence the threat is real' = emotional reasoning about the schema itself.",mechanism:"If you believe anxiety is INFORMATIVE ('I feel anxious therefore the meeting IS dangerous'), the emotional signal reinforces the schema. 'Emotional perfectionism': negative emotions should not exist and their presence indicates failure. For US: 'If I feel uncertain, something is wrong and I must fix it through more preparation.'",schemaRelevance:["Unrelenting Standards","Failure"],tags:["emotional_schema","Leahy","meta_emotion","emotional_reasoning","uncertainty_tolerance"],practice:{what:"Identify and challenge beliefs about your own emotions",how:"(1) 'If I feel anxious, the threat is real' → 'Anxiety is the schema's output, not a threat detector. I felt anxious AND regulated incidents turned out fine.' (2) 'If I feel angry at instruction, it must be wrong' → 'Anger is the Rebel's response to STRUCTURE, not content.' (3) 'If I feel uncertain, I need certainty' → 'Tolerating uncertainty IS the professional skill, not a sign of incompetence.'",when:"When you notice using emotions as evidence for the schema.",duration:"15 minutes",frequency:"Weekly review.",successMarker:"You feel anxious AND know it's not informative. Emotion exists without driving behavior."}},
  {id:"ST-19",source:"Deliberate Practice in Schema Therapy — Behary & Farrell (2023)",sourceShort:"Deliberate Practice",framework:"schema_therapy",concept_type:"deliberate_practice",name:"Deliberate Practice — Repeating Until Automatic",description:"Behary & Farrell: change through REPETITION, not insight. The Healthy Adult response must be practiced until automatic — like a musician rehearsing scales.",mechanism:"Automaticity requires ~40-60 repetitions in varied contexts. One experiment proves the schema wrong once; the schema has 7 years of DEKRA reinforcement. Deliberate practice competes with the schema's automatic output through sheer repetition.",schemaRelevance:["Unrelenting Standards","Subjugation"],tags:["deliberate_practice","repetition","automaticity","Behary","Farrell"],practice:{what:"Choose one Healthy Adult response and practice 5x daily for 2 weeks",how:"Example: 'Understood, I'll consult before externalizing.' (1) Write it 5x. (2) Say aloud 5x. (3) Imagine Mehdi's face and say it 5x. (4) Imagine the Rebel firing and STILL say it. (5) Use in next real situation. After each real use: Did it come automatically? How long was internal delay? Move to next response only when this one fires naturally.",when:"Daily morning and evening. Real application as situations arise.",duration:"5 min per session",frequency:"Twice daily for 2 weeks per response.",successMarker:"Response fires in real situation with <3 seconds delay. Rebel may flash but Healthy Adult speaks first."}},
  {id:"ST-20",source:"The Wiley-Blackwell Handbook of Schema Therapy — van Vreeswijk, Broersen & Nadort (2012)",sourceShort:"Wiley Handbook",framework:"schema_therapy",concept_type:"integrated_protocol",name:"Weekly Schema Therapy Self-Practice Protocol",description:"Integrated weekly protocol combining cognitive, experiential, and behavioral work. Structured for sustainable long-term self-directed practice.",mechanism:"Schema therapy is most effective when all three change channels are active simultaneously. Weekly structure ensures none is neglected and gives the Healthy Adult a predictable framework.",schemaRelevance:["Unrelenting Standards","Subjugation","Failure"],tags:["weekly_protocol","integrated","cognitive","experiential","behavioral","self_practice","Wiley"],practice:{what:"Follow this weekly schema therapy schedule",how:"DAILY (15 min): Schema diary + schema-focused mindfulness (5 min). MONDAY: Review past week's diary — which schemas fired? Which modes dominated? WEDNESDAY: Chair work or imagery rescripting (20-30 min) on strongest activation. FRIDAY: Behavioral experiment review — did I execute? What happened? Credit regulation. SUNDAY: Plan next week's experiment. Review flashcards. Re-read reparenting letter if needed. MONTHLY: Historical test update + rewrite flashcards.",when:"Set specific times. Non-negotiable like medication.",duration:"15 min daily. 30 min Wednesday. 15 min Fri/Sun.",frequency:"Weekly cycle. Minimum 12 weeks. Maintenance indefinitely.",successMarker:"After 12 weeks: fewer activations, faster regulation, more Healthy Adult time, soothing system activating without performance prerequisites."}}
];

async function main() {
  const uri = process.env.MONGODB_URI;
  if (!uri) throw new Error("MONGODB_URI not set");
  const client = new MongoClient(uri);
  await client.connect();
  const db = client.db("hope");
  const collections = await db.listCollections({ name: "hp" }).toArray();
  if (collections.length > 0) { await db.collection("hp").drop(); console.log("Dropped existing hp collection"); }
  await db.collection("hp").insertMany(records);
  console.log(`Seeded ${records.length} records into hp collection`);
  await db.collection("hp").createIndex({ schemaRelevance: 1 });
  await db.collection("hp").createIndex({ concept_type: 1 });
  await db.collection("hp").createIndex({ tags: 1 });
  await db.collection("hp").createIndex({ id: 1 }, { unique: true });
  console.log("Indexes created");
  const byType = records.reduce((a, r) => { a[r.concept_type] = (a[r.concept_type] || 0) + 1; return a; }, {} as Record<string, number>);
  console.log("\nBy concept type:"); Object.entries(byType).forEach(([k, v]) => console.log(`  ${k}: ${v}`));
  const bySource = records.reduce((a, r) => { a[r.sourceShort] = (a[r.sourceShort] || 0) + 1; return a; }, {} as Record<string, number>);
  console.log("\nBy source:"); Object.entries(bySource).forEach(([k, v]) => console.log(`  ${k}: ${v}`));
  await client.close();
}
main().catch(console.error);
